manifest_version = 2
name = "ecp-dns-auth"
description = "DoH Authoritative DNS Service based on the object store"
authors = ["<mark@fastly.com>"]
language = "rust"
service_id = "1qsHXbzrPme5M3iXsUjE3s"
